name: "Deploy App"

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          #Set Java Version
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      - name: Build with maven
        run: mvn -B package --file backend/pom.xml

      - uses: actions/upload-artifact@v2
        with:
          name: backend.jar
          path: backend/target/backend.jar

  push-to-docker-hub:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: backend.jar
          path: backend/target

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          #Set dockerhub username
          username: gerdloedige
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          #Set dockerhub project (replace "sergejneuefische/javafx-student-db")
          tags: gerdloedige/tixhive:latest
          context: ./backend
  deploy:
    runs-on: ubuntu-latest
    needs: push-to-docker-hub
    steps:
      - name: Restart docker container
        uses: appleboy/ssh-action@master
        with:
          host: capstone-project.de
          #Set App Name (replace "antimon" with "oxygen", "phosphorus", "mercury")
          username: muc-java-23-1-gerd
          password: ${{ secrets.SSH_PASSWORD }}
          #Set App Name (replace "antimon" with "oxygen", "phosphorus", "mercury")
          #Set dockerhub project (replace "sergejneuefische/javafx-student-db")
          #Set IP (replace "10.0.2.1" with "10.0.2.14", "10.0.2.15" or "10.0.2.16")
          script: |
            docker stop muc-java-23-1-gerd
            docker rm muc-java-23-1-gerd
            docker run --pull=always --name muc-java-23-1-gerd -e=MONGO_DB_URI=${{ secrets.MONGO_DB_URI }} --network capstones --ip 10.0.6.3 --restart always --detach gerdloedige/tixhive:latest
            sleep 15s
            docker logs muc-java-23-1-gerd

      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          #Set App Name (replace "antimon" with "oxygen", "phosphorus", "mercury")
          url: https://muc-java-23-1-gerd.capstone-project.de
          max-attempts: 3
          retry-delay: 5s
          retry-all: true
